export const GYM_LIST_MY_REQUEST = 'GYM_LIST_MY_REQUEST'
export const GYM_LIST_MY_SUCCESS = 'GYM_LIST_MY_SUCCESS'
export const GYM_LIST_MY_FAIL = 'GYM_LIST_MY_FAIL'
export const GYM_LIST_MY_RESET = 'GYM_LIST_MY_RESET'

export const GYM_LIST_REQUEST = 'GYM_LIST_REQUEST'
export const GYM_LIST_SUCCESS = 'GYM_LIST_SUCCESS'
export const GYM_LIST_FAIL = 'GYM_LIST_FAIL'

export const GYM_DETAILS_REQUEST = 'GYM_DETAILS_REQUEST'
export const GYM_DETAILS_SUCCESS = 'GYM_DETAILS_SUCCESS'
export const GYM_DETAILS_FAIL = 'GYM_DETAILS_FAIL'
export const GYM_DETAILS_RESET = 'GYM_DETAILS_RESET'

export const GYM_CREATE_REQUEST = 'GYM_CREATE_REQUEST'
export const GYM_CREATE_SUCCESS = 'GYM_CREATE_SUCCESS'
export const GYM_CREATE_FAIL = 'GYM_CREATE_FAIL'
export const GYM_CREATE_RESET = 'GYM_CREATE_RESET'

export const GYM_UPDATE_REQUEST = 'GYM_UPDATE_REQUEST'
export const GYM_UPDATE_SUCCESS = 'GYM_UPDATE_SUCCESS'
export const GYM_UPDATE_FAIL = 'GYM_UPDATE_FAIL'
export const GYM_UPDATE_RESET = 'GYM_UPDATE_RESET'

export const GYM_DELETE_REQUEST = 'GYM_DELETE_REQUEST'
export const GYM_DELETE_SUCCESS = 'GYM_DELETE_SUCCESS'
export const GYM_DELETE_FAIL = 'GYM_DELETE_FAIL'
